apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AndrewSpeelman/homelab
        revision: master
        directories:
          - path: k8s/applications/*/overlays/local
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/AndrewSpeelman/homelab
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true